/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal project scaffolds.
// Keep it committed so TypeScript understands Next app types before install.
